-- ============================================================
-- ELVARIS ERP
-- Migration 003: Seed Global Masters
--
-- Generated by:
-- scripts/generate-global-seed.mjs
--
-- Universal data:
--   Countries
--   Currencies
--   Languages
--   Units of Measure
--   Payment Terms
--
-- This migration is idempotent.
-- ============================================================


-- ============================================================
-- 1. CURRENCIES
-- ============================================================

insert into public.currencies (
  code,
  name,
  symbol,
  numeric_code,
  decimal_places,
  is_active
)
values
(
  'AED',
  'United Arab Emirates Dirham',
  'AED',
  '784',
  2,
  true
),
(
  'AFN',
  'Afghan Afghani',
  '؋',
  '971',
  2,
  true
),
(
  'ALL',
  'Albanian Lek',
  'ALL',
  '008',
  2,
  true
),
(
  'AMD',
  'Armenian Dram',
  '֏',
  '051',
  2,
  true
),
(
  'ANG',
  'Netherlands Antillean Guilder',
  'ANG',
  '532',
  2,
  true
),
(
  'AOA',
  'Angolan Kwanza',
  'Kz',
  '973',
  2,
  true
),
(
  'ARS',
  'Argentine Peso',
  '$',
  '032',
  2,
  true
),
(
  'AUD',
  'Australian Dollar',
  '$',
  '036',
  2,
  true
),
(
  'AWG',
  'Aruban Florin',
  'AWG',
  '533',
  2,
  true
),
(
  'AZN',
  'Azerbaijani Manat',
  '₼',
  '944',
  2,
  true
),
(
  'BAM',
  'Bosnia-Herzegovina Convertible Mark',
  'KM',
  '977',
  2,
  true
),
(
  'BBD',
  'Barbadian Dollar',
  '$',
  '052',
  2,
  true
),
(
  'BDT',
  'Bangladeshi Taka',
  '৳',
  '050',
  2,
  true
),
(
  'BHD',
  'Bahraini Dinar',
  'BHD',
  '048',
  3,
  true
),
(
  'BIF',
  'Burundian Franc',
  'BIF',
  '108',
  0,
  true
),
(
  'BMD',
  'Bermudan Dollar',
  '$',
  '060',
  2,
  true
),
(
  'BND',
  'Brunei Dollar',
  '$',
  '096',
  2,
  true
),
(
  'BOB',
  'Bolivian Boliviano',
  'Bs',
  '068',
  2,
  true
),
(
  'BOV',
  'Bolivian Mvdol',
  'BOV',
  '984',
  2,
  true
),
(
  'BRL',
  'Brazilian Real',
  'R$',
  '986',
  2,
  true
),
(
  'BSD',
  'Bahamian Dollar',
  '$',
  '044',
  2,
  true
),
(
  'BTN',
  'Bhutanese Ngultrum',
  'BTN',
  '064',
  2,
  true
),
(
  'BWP',
  'Botswanan Pula',
  'P',
  '072',
  2,
  true
),
(
  'BYN',
  'Belarusian Ruble',
  'BYN',
  '933',
  2,
  true
),
(
  'BZD',
  'Belize Dollar',
  '$',
  '084',
  2,
  true
),
(
  'CAD',
  'Canadian Dollar',
  '$',
  '124',
  2,
  true
),
(
  'CDF',
  'Congolese Franc',
  'CDF',
  '976',
  2,
  true
),
(
  'CHE',
  'WIR Euro',
  'CHE',
  '947',
  2,
  true
),
(
  'CHF',
  'Swiss Franc',
  'CHF',
  '756',
  2,
  true
),
(
  'CHW',
  'WIR Franc',
  'CHW',
  '948',
  2,
  true
),
(
  'CLF',
  'Chilean Unit of Account (UF)',
  'CLF',
  '990',
  4,
  true
),
(
  'CLP',
  'Chilean Peso',
  '$',
  '152',
  0,
  true
),
(
  'CNY',
  'Chinese Yuan',
  '¥',
  '156',
  2,
  true
),
(
  'COP',
  'Colombian Peso',
  '$',
  '170',
  2,
  true
),
(
  'COU',
  'Colombian Real Value Unit',
  'COU',
  '970',
  2,
  true
),
(
  'CRC',
  'Costa Rican Colón',
  '₡',
  '188',
  2,
  true
),
(
  'CUP',
  'Cuban Peso',
  '$',
  '192',
  2,
  true
),
(
  'CVE',
  'Cape Verdean Escudo',
  'CVE',
  '132',
  2,
  true
),
(
  'CZK',
  'Czech Koruna',
  'Kč',
  '203',
  2,
  true
),
(
  'DJF',
  'Djiboutian Franc',
  'DJF',
  '262',
  0,
  true
),
(
  'DKK',
  'Danish Krone',
  'kr',
  '208',
  2,
  true
),
(
  'DOP',
  'Dominican Peso',
  '$',
  '214',
  2,
  true
),
(
  'DZD',
  'Algerian Dinar',
  'DZD',
  '012',
  2,
  true
),
(
  'EGP',
  'Egyptian Pound',
  'E£',
  '818',
  2,
  true
),
(
  'ERN',
  'Eritrean Nakfa',
  'ERN',
  '232',
  2,
  true
),
(
  'ETB',
  'Ethiopian Birr',
  'ETB',
  '230',
  2,
  true
),
(
  'EUR',
  'Euro',
  '€',
  '978',
  2,
  true
),
(
  'FJD',
  'Fijian Dollar',
  '$',
  '242',
  2,
  true
),
(
  'FKP',
  'Falkland Islands Pound',
  '£',
  '238',
  2,
  true
),
(
  'GBP',
  'British Pound',
  '£',
  '826',
  2,
  true
),
(
  'GEL',
  'Georgian Lari',
  '₾',
  '981',
  2,
  true
),
(
  'GHS',
  'Ghanaian Cedi',
  'GH₵',
  '936',
  2,
  true
),
(
  'GIP',
  'Gibraltar Pound',
  '£',
  '292',
  2,
  true
),
(
  'GMD',
  'Gambian Dalasi',
  'GMD',
  '270',
  2,
  true
),
(
  'GNF',
  'Guinean Franc',
  'FG',
  '324',
  0,
  true
),
(
  'GTQ',
  'Guatemalan Quetzal',
  'Q',
  '320',
  2,
  true
),
(
  'GYD',
  'Guyanese Dollar',
  '$',
  '328',
  2,
  true
),
(
  'HKD',
  'Hong Kong Dollar',
  '$',
  '344',
  2,
  true
),
(
  'HNL',
  'Honduran Lempira',
  'L',
  '340',
  2,
  true
),
(
  'HTG',
  'Haitian Gourde',
  'HTG',
  '332',
  2,
  true
),
(
  'HUF',
  'Hungarian Forint',
  'Ft',
  '348',
  2,
  true
),
(
  'IDR',
  'Indonesian Rupiah',
  'Rp',
  '360',
  2,
  true
),
(
  'ILS',
  'Israeli New Shekel',
  '₪',
  '376',
  2,
  true
),
(
  'INR',
  'Indian Rupee',
  '₹',
  '356',
  2,
  true
),
(
  'IQD',
  'Iraqi Dinar',
  'IQD',
  '368',
  3,
  true
),
(
  'IRR',
  'Iranian Rial',
  'IRR',
  '364',
  2,
  true
),
(
  'ISK',
  'Icelandic Króna',
  'kr',
  '352',
  0,
  true
),
(
  'JMD',
  'Jamaican Dollar',
  '$',
  '388',
  2,
  true
),
(
  'JOD',
  'Jordanian Dinar',
  'JOD',
  '400',
  3,
  true
),
(
  'JPY',
  'Japanese Yen',
  '¥',
  '392',
  0,
  true
),
(
  'KES',
  'Kenyan Shilling',
  'KES',
  '404',
  2,
  true
),
(
  'KGS',
  'Kyrgyz Som',
  '⃀',
  '417',
  2,
  true
),
(
  'KHR',
  'Cambodian Riel',
  '៛',
  '116',
  2,
  true
),
(
  'KMF',
  'Comorian Franc',
  'CF',
  '174',
  0,
  true
),
(
  'KPW',
  'North Korean Won',
  '₩',
  '408',
  2,
  true
),
(
  'KRW',
  'South Korean Won',
  '₩',
  '410',
  0,
  true
),
(
  'KWD',
  'Kuwaiti Dinar',
  'KWD',
  '414',
  3,
  true
),
(
  'KYD',
  'Cayman Islands Dollar',
  '$',
  '136',
  2,
  true
),
(
  'KZT',
  'Kazakhstani Tenge',
  '₸',
  '398',
  2,
  true
),
(
  'LAK',
  'Laotian Kip',
  '₭',
  '418',
  2,
  true
),
(
  'LBP',
  'Lebanese Pound',
  'L£',
  '422',
  2,
  true
),
(
  'LKR',
  'Sri Lankan Rupee',
  'Rs',
  '144',
  2,
  true
),
(
  'LRD',
  'Liberian Dollar',
  '$',
  '430',
  2,
  true
),
(
  'LSL',
  'Lesotho Loti',
  'LSL',
  '426',
  2,
  true
),
(
  'LYD',
  'Libyan Dinar',
  'LYD',
  '434',
  3,
  true
),
(
  'MAD',
  'Moroccan Dirham',
  'MAD',
  '504',
  2,
  true
),
(
  'MDL',
  'Moldovan Leu',
  'MDL',
  '498',
  2,
  true
),
(
  'MGA',
  'Malagasy Ariary',
  'Ar',
  '969',
  2,
  true
),
(
  'MKD',
  'Macedonian Denar',
  'MKD',
  '807',
  2,
  true
),
(
  'MMK',
  'Myanmar Kyat',
  'K',
  '104',
  2,
  true
),
(
  'MNT',
  'Mongolian Tugrik',
  '₮',
  '496',
  2,
  true
),
(
  'MOP',
  'Macanese Pataca',
  'MOP',
  '446',
  2,
  true
),
(
  'MRU',
  'Mauritanian Ouguiya',
  'MRU',
  '929',
  2,
  true
),
(
  'MUR',
  'Mauritian Rupee',
  'Rs',
  '480',
  2,
  true
),
(
  'MVR',
  'Maldivian Rufiyaa',
  'MVR',
  '462',
  2,
  true
),
(
  'MWK',
  'Malawian Kwacha',
  'MWK',
  '454',
  2,
  true
),
(
  'MXN',
  'Mexican Peso',
  '$',
  '484',
  2,
  true
),
(
  'MXV',
  'Mexican Investment Unit',
  'MXV',
  '979',
  2,
  true
),
(
  'MYR',
  'Malaysian Ringgit',
  'RM',
  '458',
  2,
  true
),
(
  'MZN',
  'Mozambican Metical',
  'MZN',
  '943',
  2,
  true
),
(
  'NAD',
  'Namibian Dollar',
  '$',
  '516',
  2,
  true
),
(
  'NGN',
  'Nigerian Naira',
  '₦',
  '566',
  2,
  true
),
(
  'NIO',
  'Nicaraguan Córdoba',
  'C$',
  '558',
  2,
  true
),
(
  'NOK',
  'Norwegian Krone',
  'kr',
  '578',
  2,
  true
),
(
  'NPR',
  'Nepalese Rupee',
  'Rs',
  '524',
  2,
  true
),
(
  'NZD',
  'New Zealand Dollar',
  '$',
  '554',
  2,
  true
),
(
  'OMR',
  'Omani Rial',
  'OMR',
  '512',
  3,
  true
),
(
  'PAB',
  'Panamanian Balboa',
  'PAB',
  '590',
  2,
  true
),
(
  'PEN',
  'Peruvian Sol',
  'PEN',
  '604',
  2,
  true
),
(
  'PGK',
  'Papua New Guinean Kina',
  'PGK',
  '598',
  2,
  true
),
(
  'PHP',
  'Philippine Peso',
  '₱',
  '608',
  2,
  true
),
(
  'PKR',
  'Pakistani Rupee',
  'Rs',
  '586',
  2,
  true
),
(
  'PLN',
  'Polish Zloty',
  'zł',
  '985',
  2,
  true
),
(
  'PYG',
  'Paraguayan Guarani',
  '₲',
  '600',
  0,
  true
),
(
  'QAR',
  'Qatari Riyal',
  'QAR',
  '634',
  2,
  true
),
(
  'RON',
  'Romanian Leu',
  'lei',
  '946',
  2,
  true
),
(
  'RSD',
  'Serbian Dinar',
  'RSD',
  '941',
  2,
  true
),
(
  'RUB',
  'Russian Ruble',
  '₽',
  '643',
  2,
  true
),
(
  'RWF',
  'Rwandan Franc',
  'RF',
  '646',
  0,
  true
),
(
  'SAR',
  'Saudi Riyal',
  'SAR',
  '682',
  2,
  true
),
(
  'SBD',
  'Solomon Islands Dollar',
  '$',
  '090',
  2,
  true
),
(
  'SCR',
  'Seychellois Rupee',
  'SCR',
  '690',
  2,
  true
),
(
  'SDG',
  'Sudanese Pound',
  'SDG',
  '938',
  2,
  true
),
(
  'SEK',
  'Swedish Krona',
  'kr',
  '752',
  2,
  true
),
(
  'SGD',
  'Singapore Dollar',
  '$',
  '702',
  2,
  true
),
(
  'SHP',
  'St. Helena Pound',
  '£',
  '654',
  2,
  true
),
(
  'SLE',
  'Sierra Leonean Leone',
  'SLE',
  '925',
  2,
  true
),
(
  'SLL',
  'Sierra Leonean Leone',
  'SLL',
  '694',
  2,
  true
),
(
  'SOS',
  'Somali Shilling',
  'SOS',
  '706',
  2,
  true
),
(
  'SRD',
  'Surinamese Dollar',
  '$',
  '968',
  2,
  true
),
(
  'SSP',
  'South Sudanese Pound',
  '£',
  '728',
  2,
  true
),
(
  'STN',
  'São Tomé & Príncipe Dobra',
  'Db',
  '930',
  2,
  true
),
(
  'SVC',
  'Salvadoran Colón',
  'SVC',
  '222',
  2,
  true
),
(
  'SYP',
  'Syrian Pound',
  '£',
  '760',
  2,
  true
),
(
  'SZL',
  'Swazi Lilangeni',
  'SZL',
  '748',
  2,
  true
),
(
  'THB',
  'Thai Baht',
  '฿',
  '764',
  2,
  true
),
(
  'TJS',
  'Tajikistani Somoni',
  'TJS',
  '972',
  2,
  true
),
(
  'TMT',
  'Turkmenistani Manat',
  'TMT',
  '934',
  2,
  true
),
(
  'TND',
  'Tunisian Dinar',
  'TND',
  '788',
  3,
  true
),
(
  'TOP',
  'Tongan Paʻanga',
  'T$',
  '776',
  2,
  true
),
(
  'TRY',
  'Turkish Lira',
  '₺',
  '949',
  2,
  true
),
(
  'TTD',
  'Trinidad & Tobago Dollar',
  '$',
  '780',
  2,
  true
),
(
  'TWD',
  'New Taiwan Dollar',
  '$',
  '901',
  2,
  true
),
(
  'TZS',
  'Tanzanian Shilling',
  'TZS',
  '834',
  2,
  true
),
(
  'UAH',
  'Ukrainian Hryvnia',
  '₴',
  '980',
  2,
  true
),
(
  'UGX',
  'Ugandan Shilling',
  'UGX',
  '800',
  0,
  true
),
(
  'USD',
  'US Dollar',
  '$',
  '840',
  2,
  true
),
(
  'USN',
  'US Dollar (Next day)',
  'USN',
  '997',
  2,
  true
),
(
  'USS',
  'US Dollar (Same day)',
  'USS',
  '998',
  2,
  true
),
(
  'UYI',
  'Uruguayan Peso (Indexed Units)',
  'UYI',
  '940',
  0,
  true
),
(
  'UYU',
  'Uruguayan Peso',
  '$',
  '858',
  2,
  true
),
(
  'UYW',
  'Uruguayan Nominal Wage Index Unit',
  'UYW',
  '927',
  4,
  true
),
(
  'UZS',
  'Uzbekistani Som',
  'UZS',
  '860',
  2,
  true
),
(
  'VED',
  'Bolívar Soberano',
  'VED',
  '926',
  2,
  true
),
(
  'VES',
  'Venezuelan Bolívar',
  'VES',
  '928',
  2,
  true
),
(
  'VND',
  'Vietnamese Dong',
  '₫',
  '704',
  0,
  true
),
(
  'VUV',
  'Vanuatu Vatu',
  'VUV',
  '548',
  0,
  true
),
(
  'WST',
  'Samoan Tala',
  'WST',
  '882',
  2,
  true
),
(
  'XAD',
  'Arab Accounting Dinar',
  'XAD',
  '396',
  2,
  true
),
(
  'XAF',
  'Central African CFA Franc',
  'FCFA',
  '950',
  0,
  true
),
(
  'XAG',
  'Silver',
  'XAG',
  '961',
  0,
  true
),
(
  'XAU',
  'Gold',
  'XAU',
  '959',
  0,
  true
),
(
  'XBA',
  'European Composite Unit',
  'XBA',
  '955',
  0,
  true
),
(
  'XBB',
  'European Monetary Unit',
  'XBB',
  '956',
  0,
  true
),
(
  'XBC',
  'European Unit of Account (XBC)',
  'XBC',
  '957',
  0,
  true
),
(
  'XBD',
  'European Unit of Account (XBD)',
  'XBD',
  '958',
  0,
  true
),
(
  'XCD',
  'East Caribbean Dollar',
  '$',
  '951',
  2,
  true
),
(
  'XCG',
  'Caribbean guilder',
  'Cg',
  '532',
  2,
  true
),
(
  'XDR',
  'Special Drawing Rights',
  'XDR',
  '960',
  0,
  true
),
(
  'XOF',
  'West African CFA Franc',
  'F CFA',
  '952',
  0,
  true
),
(
  'XPD',
  'Palladium',
  'XPD',
  '964',
  0,
  true
),
(
  'XPF',
  'CFP Franc',
  'CFPF',
  '953',
  0,
  true
),
(
  'XPT',
  'Platinum',
  'XPT',
  '962',
  0,
  true
),
(
  'XSU',
  'Sucre',
  'XSU',
  '994',
  0,
  true
),
(
  'XTS',
  'Testing Currency Code',
  'XTS',
  '963',
  0,
  true
),
(
  'XUA',
  'ADB Unit of Account',
  'XUA',
  '965',
  0,
  true
),
(
  'XXX',
  'Unknown Currency',
  '¤',
  '999',
  0,
  true
),
(
  'YER',
  'Yemeni Rial',
  'YER',
  '886',
  2,
  true
),
(
  'ZAR',
  'South African Rand',
  'R',
  '710',
  2,
  true
),
(
  'ZMW',
  'Zambian Kwacha',
  'ZK',
  '967',
  2,
  true
),
(
  'ZWG',
  'Zimbabwean Gold',
  'ZWG',
  '924',
  2,
  true
)
on conflict (code)
do update set
  name = excluded.name,
  symbol = excluded.symbol,
  numeric_code = excluded.numeric_code,
  decimal_places = excluded.decimal_places,
  is_active = true,
  updated_at = now();


-- ============================================================
-- 2. COUNTRIES
-- ============================================================

insert into public.countries (
  name,
  iso2_code,
  iso3_code,
  numeric_code,
  phone_code,
  is_active
)
values
(
  'Afghanistan',
  'AF',
  null,
  null,
  '+93',
  true
),
(
  'Aland',
  'AX',
  null,
  null,
  '+358',
  true
),
(
  'Albania',
  'AL',
  null,
  null,
  '+355',
  true
),
(
  'Algeria',
  'DZ',
  null,
  null,
  '+213',
  true
),
(
  'American Samoa',
  'AS',
  null,
  null,
  '+1684',
  true
),
(
  'Andorra',
  'AD',
  null,
  null,
  '+376',
  true
),
(
  'Angola',
  'AO',
  null,
  null,
  '+244',
  true
),
(
  'Anguilla',
  'AI',
  null,
  null,
  '+1264',
  true
),
(
  'Antarctica',
  'AQ',
  null,
  null,
  '+672',
  true
),
(
  'Antigua and Barbuda',
  'AG',
  null,
  null,
  '+1268',
  true
),
(
  'Argentina',
  'AR',
  null,
  null,
  '+54',
  true
),
(
  'Armenia',
  'AM',
  null,
  null,
  '+374',
  true
),
(
  'Aruba',
  'AW',
  null,
  null,
  '+297',
  true
),
(
  'Ascension Island',
  'AC',
  null,
  null,
  '+247',
  true
),
(
  'Australia',
  'AU',
  null,
  null,
  '+61',
  true
),
(
  'Austria',
  'AT',
  null,
  null,
  '+43',
  true
),
(
  'Azerbaijan',
  'AZ',
  null,
  null,
  '+994',
  true
),
(
  'Bahamas',
  'BS',
  null,
  null,
  '+1242',
  true
),
(
  'Bahrain',
  'BH',
  null,
  null,
  '+973',
  true
),
(
  'Bangladesh',
  'BD',
  null,
  null,
  '+880',
  true
),
(
  'Barbados',
  'BB',
  null,
  null,
  '+1246',
  true
),
(
  'Belarus',
  'BY',
  null,
  null,
  '+375',
  true
),
(
  'Belgium',
  'BE',
  null,
  null,
  '+32',
  true
),
(
  'Belize',
  'BZ',
  null,
  null,
  '+501',
  true
),
(
  'Benin',
  'BJ',
  null,
  null,
  '+229',
  true
),
(
  'Bermuda',
  'BM',
  null,
  null,
  '+1441',
  true
),
(
  'Bhutan',
  'BT',
  null,
  null,
  '+975',
  true
),
(
  'Bolivia',
  'BO',
  null,
  null,
  '+591',
  true
),
(
  'Bonaire',
  'BQ',
  null,
  null,
  '+5997',
  true
),
(
  'Bosnia and Herzegovina',
  'BA',
  null,
  null,
  '+387',
  true
),
(
  'Botswana',
  'BW',
  null,
  null,
  '+267',
  true
),
(
  'Bouvet Island',
  'BV',
  null,
  null,
  '+47',
  true
),
(
  'Brazil',
  'BR',
  null,
  null,
  '+55',
  true
),
(
  'British Indian Ocean Territory',
  'IO',
  null,
  null,
  '+246',
  true
),
(
  'British Virgin Islands',
  'VG',
  null,
  null,
  '+1284',
  true
),
(
  'Brunei',
  'BN',
  null,
  null,
  '+673',
  true
),
(
  'Bulgaria',
  'BG',
  null,
  null,
  '+359',
  true
),
(
  'Burkina Faso',
  'BF',
  null,
  null,
  '+226',
  true
),
(
  'Burundi',
  'BI',
  null,
  null,
  '+257',
  true
),
(
  'Cabo Verde',
  'CV',
  null,
  null,
  '+238',
  true
),
(
  'Cambodia',
  'KH',
  null,
  null,
  '+855',
  true
),
(
  'Cameroon',
  'CM',
  null,
  null,
  '+237',
  true
),
(
  'Canada',
  'CA',
  null,
  null,
  '+1',
  true
),
(
  'Cayman Islands',
  'KY',
  null,
  null,
  '+1345',
  true
),
(
  'Central African Republic',
  'CF',
  null,
  null,
  '+236',
  true
),
(
  'Chad',
  'TD',
  null,
  null,
  '+235',
  true
),
(
  'Chile',
  'CL',
  null,
  null,
  '+56',
  true
),
(
  'China',
  'CN',
  null,
  null,
  '+86',
  true
),
(
  'Christmas Island',
  'CX',
  null,
  null,
  '+61',
  true
),
(
  'Cocos (Keeling) Islands',
  'CC',
  null,
  null,
  '+61',
  true
),
(
  'Colombia',
  'CO',
  null,
  null,
  '+57',
  true
),
(
  'Comoros',
  'KM',
  null,
  null,
  '+269',
  true
),
(
  'Cook Islands',
  'CK',
  null,
  null,
  '+682',
  true
),
(
  'Costa Rica',
  'CR',
  null,
  null,
  '+506',
  true
),
(
  'Croatia',
  'HR',
  null,
  null,
  '+385',
  true
),
(
  'Cuba',
  'CU',
  null,
  null,
  '+53',
  true
),
(
  'Curacao',
  'CW',
  null,
  null,
  '+5999',
  true
),
(
  'Cyprus',
  'CY',
  null,
  null,
  '+357',
  true
),
(
  'Czechia',
  'CZ',
  null,
  null,
  '+420',
  true
),
(
  'Democratic Republic of the Congo',
  'CD',
  null,
  null,
  '+243',
  true
),
(
  'Denmark',
  'DK',
  null,
  null,
  '+45',
  true
),
(
  'Djibouti',
  'DJ',
  null,
  null,
  '+253',
  true
),
(
  'Dominica',
  'DM',
  null,
  null,
  '+1767',
  true
),
(
  'Dominican Republic',
  'DO',
  null,
  null,
  '+1809',
  true
),
(
  'East Timor',
  'TL',
  null,
  null,
  '+670',
  true
),
(
  'Ecuador',
  'EC',
  null,
  null,
  '+593',
  true
),
(
  'Egypt',
  'EG',
  null,
  null,
  '+20',
  true
),
(
  'El Salvador',
  'SV',
  null,
  null,
  '+503',
  true
),
(
  'Equatorial Guinea',
  'GQ',
  null,
  null,
  '+240',
  true
),
(
  'Eritrea',
  'ER',
  null,
  null,
  '+291',
  true
),
(
  'Estonia',
  'EE',
  null,
  null,
  '+372',
  true
),
(
  'Eswatini',
  'SZ',
  null,
  null,
  '+268',
  true
),
(
  'Ethiopia',
  'ET',
  null,
  null,
  '+251',
  true
),
(
  'Falkland Islands',
  'FK',
  null,
  null,
  '+500',
  true
),
(
  'Faroe Islands',
  'FO',
  null,
  null,
  '+298',
  true
),
(
  'Fiji',
  'FJ',
  null,
  null,
  '+679',
  true
),
(
  'Finland',
  'FI',
  null,
  null,
  '+358',
  true
),
(
  'France',
  'FR',
  null,
  null,
  '+33',
  true
),
(
  'French Guiana',
  'GF',
  null,
  null,
  '+594',
  true
),
(
  'French Polynesia',
  'PF',
  null,
  null,
  '+689',
  true
),
(
  'French Southern Territories',
  'TF',
  null,
  null,
  '+262',
  true
),
(
  'Gabon',
  'GA',
  null,
  null,
  '+241',
  true
),
(
  'Gambia',
  'GM',
  null,
  null,
  '+220',
  true
),
(
  'Georgia',
  'GE',
  null,
  null,
  '+995',
  true
),
(
  'Germany',
  'DE',
  null,
  null,
  '+49',
  true
),
(
  'Ghana',
  'GH',
  null,
  null,
  '+233',
  true
),
(
  'Gibraltar',
  'GI',
  null,
  null,
  '+350',
  true
),
(
  'Greece',
  'GR',
  null,
  null,
  '+30',
  true
),
(
  'Greenland',
  'GL',
  null,
  null,
  '+299',
  true
),
(
  'Grenada',
  'GD',
  null,
  null,
  '+1473',
  true
),
(
  'Guadeloupe',
  'GP',
  null,
  null,
  '+590',
  true
),
(
  'Guam',
  'GU',
  null,
  null,
  '+1671',
  true
),
(
  'Guatemala',
  'GT',
  null,
  null,
  '+502',
  true
),
(
  'Guernsey',
  'GG',
  null,
  null,
  '+44',
  true
),
(
  'Guinea',
  'GN',
  null,
  null,
  '+224',
  true
),
(
  'Guinea-Bissau',
  'GW',
  null,
  null,
  '+245',
  true
),
(
  'Guyana',
  'GY',
  null,
  null,
  '+592',
  true
),
(
  'Haiti',
  'HT',
  null,
  null,
  '+509',
  true
),
(
  'Heard Island and McDonald Islands',
  'HM',
  null,
  null,
  '+61',
  true
),
(
  'Honduras',
  'HN',
  null,
  null,
  '+504',
  true
),
(
  'Hong Kong',
  'HK',
  null,
  null,
  '+852',
  true
),
(
  'Hungary',
  'HU',
  null,
  null,
  '+36',
  true
),
(
  'Iceland',
  'IS',
  null,
  null,
  '+354',
  true
),
(
  'India',
  'IN',
  null,
  null,
  '+91',
  true
),
(
  'Indonesia',
  'ID',
  null,
  null,
  '+62',
  true
),
(
  'Iran',
  'IR',
  null,
  null,
  '+98',
  true
),
(
  'Iraq',
  'IQ',
  null,
  null,
  '+964',
  true
),
(
  'Ireland',
  'IE',
  null,
  null,
  '+353',
  true
),
(
  'Isle of Man',
  'IM',
  null,
  null,
  '+44',
  true
),
(
  'Israel',
  'IL',
  null,
  null,
  '+972',
  true
),
(
  'Italy',
  'IT',
  null,
  null,
  '+39',
  true
),
(
  'Ivory Coast',
  'CI',
  null,
  null,
  '+225',
  true
),
(
  'Jamaica',
  'JM',
  null,
  null,
  '+1876',
  true
),
(
  'Japan',
  'JP',
  null,
  null,
  '+81',
  true
),
(
  'Jersey',
  'JE',
  null,
  null,
  '+44',
  true
),
(
  'Jordan',
  'JO',
  null,
  null,
  '+962',
  true
),
(
  'Kazakhstan',
  'KZ',
  null,
  null,
  '+7',
  true
),
(
  'Kenya',
  'KE',
  null,
  null,
  '+254',
  true
),
(
  'Kiribati',
  'KI',
  null,
  null,
  '+686',
  true
),
(
  'Kosovo',
  'XK',
  null,
  null,
  '+377',
  true
),
(
  'Kuwait',
  'KW',
  null,
  null,
  '+965',
  true
),
(
  'Kyrgyzstan',
  'KG',
  null,
  null,
  '+996',
  true
),
(
  'Laos',
  'LA',
  null,
  null,
  '+856',
  true
),
(
  'Latvia',
  'LV',
  null,
  null,
  '+371',
  true
),
(
  'Lebanon',
  'LB',
  null,
  null,
  '+961',
  true
),
(
  'Lesotho',
  'LS',
  null,
  null,
  '+266',
  true
),
(
  'Liberia',
  'LR',
  null,
  null,
  '+231',
  true
),
(
  'Libya',
  'LY',
  null,
  null,
  '+218',
  true
),
(
  'Liechtenstein',
  'LI',
  null,
  null,
  '+423',
  true
),
(
  'Lithuania',
  'LT',
  null,
  null,
  '+370',
  true
),
(
  'Luxembourg',
  'LU',
  null,
  null,
  '+352',
  true
),
(
  'Macao',
  'MO',
  null,
  null,
  '+853',
  true
),
(
  'Madagascar',
  'MG',
  null,
  null,
  '+261',
  true
),
(
  'Malawi',
  'MW',
  null,
  null,
  '+265',
  true
),
(
  'Malaysia',
  'MY',
  null,
  null,
  '+60',
  true
),
(
  'Maldives',
  'MV',
  null,
  null,
  '+960',
  true
),
(
  'Mali',
  'ML',
  null,
  null,
  '+223',
  true
),
(
  'Malta',
  'MT',
  null,
  null,
  '+356',
  true
),
(
  'Marshall Islands',
  'MH',
  null,
  null,
  '+692',
  true
),
(
  'Martinique',
  'MQ',
  null,
  null,
  '+596',
  true
),
(
  'Mauritania',
  'MR',
  null,
  null,
  '+222',
  true
),
(
  'Mauritius',
  'MU',
  null,
  null,
  '+230',
  true
),
(
  'Mayotte',
  'YT',
  null,
  null,
  '+262',
  true
),
(
  'Mexico',
  'MX',
  null,
  null,
  '+52',
  true
),
(
  'Micronesia',
  'FM',
  null,
  null,
  '+691',
  true
),
(
  'Moldova',
  'MD',
  null,
  null,
  '+373',
  true
),
(
  'Monaco',
  'MC',
  null,
  null,
  '+377',
  true
),
(
  'Mongolia',
  'MN',
  null,
  null,
  '+976',
  true
),
(
  'Montenegro',
  'ME',
  null,
  null,
  '+382',
  true
),
(
  'Montserrat',
  'MS',
  null,
  null,
  '+1664',
  true
),
(
  'Morocco',
  'MA',
  null,
  null,
  '+212',
  true
),
(
  'Mozambique',
  'MZ',
  null,
  null,
  '+258',
  true
),
(
  'Myanmar',
  'MM',
  null,
  null,
  '+95',
  true
),
(
  'Namibia',
  'NA',
  null,
  null,
  '+264',
  true
),
(
  'Nauru',
  'NR',
  null,
  null,
  '+674',
  true
),
(
  'Nepal',
  'NP',
  null,
  null,
  '+977',
  true
),
(
  'Netherlands',
  'NL',
  null,
  null,
  '+31',
  true
),
(
  'New Caledonia',
  'NC',
  null,
  null,
  '+687',
  true
),
(
  'New Zealand',
  'NZ',
  null,
  null,
  '+64',
  true
),
(
  'Nicaragua',
  'NI',
  null,
  null,
  '+505',
  true
),
(
  'Niger',
  'NE',
  null,
  null,
  '+227',
  true
),
(
  'Nigeria',
  'NG',
  null,
  null,
  '+234',
  true
),
(
  'Niue',
  'NU',
  null,
  null,
  '+683',
  true
),
(
  'Norfolk Island',
  'NF',
  null,
  null,
  '+672',
  true
),
(
  'North Korea',
  'KP',
  null,
  null,
  '+850',
  true
),
(
  'North Macedonia',
  'MK',
  null,
  null,
  '+389',
  true
),
(
  'Northern Mariana Islands',
  'MP',
  null,
  null,
  '+1670',
  true
),
(
  'Norway',
  'NO',
  null,
  null,
  '+47',
  true
),
(
  'Oman',
  'OM',
  null,
  null,
  '+968',
  true
),
(
  'Pakistan',
  'PK',
  null,
  null,
  '+92',
  true
),
(
  'Palau',
  'PW',
  null,
  null,
  '+680',
  true
),
(
  'Palestine',
  'PS',
  null,
  null,
  '+970',
  true
),
(
  'Panama',
  'PA',
  null,
  null,
  '+507',
  true
),
(
  'Papua New Guinea',
  'PG',
  null,
  null,
  '+675',
  true
),
(
  'Paraguay',
  'PY',
  null,
  null,
  '+595',
  true
),
(
  'Peru',
  'PE',
  null,
  null,
  '+51',
  true
),
(
  'Philippines',
  'PH',
  null,
  null,
  '+63',
  true
),
(
  'Pitcairn Islands',
  'PN',
  null,
  null,
  '+64',
  true
),
(
  'Poland',
  'PL',
  null,
  null,
  '+48',
  true
),
(
  'Portugal',
  'PT',
  null,
  null,
  '+351',
  true
),
(
  'Puerto Rico',
  'PR',
  null,
  null,
  '+1787',
  true
),
(
  'Qatar',
  'QA',
  null,
  null,
  '+974',
  true
),
(
  'Republic of the Congo',
  'CG',
  null,
  null,
  '+242',
  true
),
(
  'Reunion',
  'RE',
  null,
  null,
  '+262',
  true
),
(
  'Romania',
  'RO',
  null,
  null,
  '+40',
  true
),
(
  'Russia',
  'RU',
  null,
  null,
  '+7',
  true
),
(
  'Rwanda',
  'RW',
  null,
  null,
  '+250',
  true
),
(
  'Saint Barthelemy',
  'BL',
  null,
  null,
  '+590',
  true
),
(
  'Saint Helena',
  'SH',
  null,
  null,
  '+290',
  true
),
(
  'Saint Kitts and Nevis',
  'KN',
  null,
  null,
  '+1869',
  true
),
(
  'Saint Lucia',
  'LC',
  null,
  null,
  '+1758',
  true
),
(
  'Saint Martin',
  'MF',
  null,
  null,
  '+590',
  true
),
(
  'Saint Pierre and Miquelon',
  'PM',
  null,
  null,
  '+508',
  true
),
(
  'Saint Vincent and the Grenadines',
  'VC',
  null,
  null,
  '+1784',
  true
),
(
  'Samoa',
  'WS',
  null,
  null,
  '+685',
  true
),
(
  'San Marino',
  'SM',
  null,
  null,
  '+378',
  true
),
(
  'Sao Tome and Principe',
  'ST',
  null,
  null,
  '+239',
  true
),
(
  'Saudi Arabia',
  'SA',
  null,
  null,
  '+966',
  true
),
(
  'Senegal',
  'SN',
  null,
  null,
  '+221',
  true
),
(
  'Serbia',
  'RS',
  null,
  null,
  '+381',
  true
),
(
  'Seychelles',
  'SC',
  null,
  null,
  '+248',
  true
),
(
  'Sierra Leone',
  'SL',
  null,
  null,
  '+232',
  true
),
(
  'Singapore',
  'SG',
  null,
  null,
  '+65',
  true
),
(
  'Sint Maarten',
  'SX',
  null,
  null,
  '+1721',
  true
),
(
  'Slovakia',
  'SK',
  null,
  null,
  '+421',
  true
),
(
  'Slovenia',
  'SI',
  null,
  null,
  '+386',
  true
),
(
  'Solomon Islands',
  'SB',
  null,
  null,
  '+677',
  true
),
(
  'Somalia',
  'SO',
  null,
  null,
  '+252',
  true
),
(
  'South Africa',
  'ZA',
  null,
  null,
  '+27',
  true
),
(
  'South Georgia and the South Sandwich Islands',
  'GS',
  null,
  null,
  '+500',
  true
),
(
  'South Korea',
  'KR',
  null,
  null,
  '+82',
  true
),
(
  'South Sudan',
  'SS',
  null,
  null,
  '+211',
  true
),
(
  'Spain',
  'ES',
  null,
  null,
  '+34',
  true
),
(
  'Sri Lanka',
  'LK',
  null,
  null,
  '+94',
  true
),
(
  'Sudan',
  'SD',
  null,
  null,
  '+249',
  true
),
(
  'Suriname',
  'SR',
  null,
  null,
  '+597',
  true
),
(
  'Svalbard and Jan Mayen',
  'SJ',
  null,
  null,
  '+4779',
  true
),
(
  'Sweden',
  'SE',
  null,
  null,
  '+46',
  true
),
(
  'Switzerland',
  'CH',
  null,
  null,
  '+41',
  true
),
(
  'Syria',
  'SY',
  null,
  null,
  '+963',
  true
),
(
  'Taiwan',
  'TW',
  null,
  null,
  '+886',
  true
),
(
  'Tajikistan',
  'TJ',
  null,
  null,
  '+992',
  true
),
(
  'Tanzania',
  'TZ',
  null,
  null,
  '+255',
  true
),
(
  'Thailand',
  'TH',
  null,
  null,
  '+66',
  true
),
(
  'Togo',
  'TG',
  null,
  null,
  '+228',
  true
),
(
  'Tokelau',
  'TK',
  null,
  null,
  '+690',
  true
),
(
  'Tonga',
  'TO',
  null,
  null,
  '+676',
  true
),
(
  'Trinidad and Tobago',
  'TT',
  null,
  null,
  '+1868',
  true
),
(
  'Tristan da Cunha',
  'TA',
  null,
  null,
  '+290',
  true
),
(
  'Tunisia',
  'TN',
  null,
  null,
  '+216',
  true
),
(
  'Türkiye',
  'TR',
  null,
  null,
  '+90',
  true
),
(
  'Turkmenistan',
  'TM',
  null,
  null,
  '+993',
  true
),
(
  'Turks and Caicos Islands',
  'TC',
  null,
  null,
  '+1649',
  true
),
(
  'Tuvalu',
  'TV',
  null,
  null,
  '+688',
  true
),
(
  'U.S. Minor Outlying Islands',
  'UM',
  null,
  null,
  '+1',
  true
),
(
  'U.S. Virgin Islands',
  'VI',
  null,
  null,
  '+1340',
  true
),
(
  'Uganda',
  'UG',
  null,
  null,
  '+256',
  true
),
(
  'Ukraine',
  'UA',
  null,
  null,
  '+380',
  true
),
(
  'United Arab Emirates',
  'AE',
  null,
  null,
  '+971',
  true
),
(
  'United Kingdom',
  'GB',
  null,
  null,
  '+44',
  true
),
(
  'United States',
  'US',
  null,
  null,
  '+1',
  true
),
(
  'Uruguay',
  'UY',
  null,
  null,
  '+598',
  true
),
(
  'Uzbekistan',
  'UZ',
  null,
  null,
  '+998',
  true
),
(
  'Vanuatu',
  'VU',
  null,
  null,
  '+678',
  true
),
(
  'Vatican City',
  'VA',
  null,
  null,
  '+379',
  true
),
(
  'Venezuela',
  'VE',
  null,
  null,
  '+58',
  true
),
(
  'Vietnam',
  'VN',
  null,
  null,
  '+84',
  true
),
(
  'Wallis and Futuna',
  'WF',
  null,
  null,
  '+681',
  true
),
(
  'Western Sahara',
  'EH',
  null,
  null,
  '+212',
  true
),
(
  'Yemen',
  'YE',
  null,
  null,
  '+967',
  true
),
(
  'Zambia',
  'ZM',
  null,
  null,
  '+260',
  true
),
(
  'Zimbabwe',
  'ZW',
  null,
  null,
  '+263',
  true
)
on conflict (iso2_code)
do update set
  name = excluded.name,
  iso3_code = excluded.iso3_code,
  numeric_code = excluded.numeric_code,
  phone_code = excluded.phone_code,
  is_active = true,
  updated_at = now();


-- ============================================================
-- 3. LANGUAGES
-- ============================================================

insert into public.languages (
  code,
  name,
  is_active
)
values
(
  'aa',
  'Afar',
  true
),
(
  'ab',
  'Abkhazian',
  true
),
(
  'af',
  'Afrikaans',
  true
),
(
  'ak',
  'Akan',
  true
),
(
  'am',
  'Amharic',
  true
),
(
  'an',
  'Aragonese',
  true
),
(
  'ar',
  'Arabic',
  true
),
(
  'as',
  'Assamese',
  true
),
(
  'av',
  'Avar',
  true
),
(
  'ay',
  'Aymara',
  true
),
(
  'az',
  'Azerbaijani',
  true
),
(
  'ba',
  'Bashkir',
  true
),
(
  'be',
  'Belarusian',
  true
),
(
  'bg',
  'Bulgarian',
  true
),
(
  'bh',
  'Bihari',
  true
),
(
  'bi',
  'Bislama',
  true
),
(
  'bm',
  'Bambara',
  true
),
(
  'bn',
  'Bengali',
  true
),
(
  'bo',
  'Tibetan',
  true
),
(
  'br',
  'Breton',
  true
),
(
  'bs',
  'Bosnian',
  true
),
(
  'ca',
  'Catalan',
  true
),
(
  'ce',
  'Chechen',
  true
),
(
  'ch',
  'Chamorro',
  true
),
(
  'co',
  'Corsican',
  true
),
(
  'cr',
  'Cree',
  true
),
(
  'cs',
  'Czech',
  true
),
(
  'cu',
  'Old Church Slavonic / Old Bulgarian',
  true
),
(
  'cv',
  'Chuvash',
  true
),
(
  'cy',
  'Welsh',
  true
),
(
  'da',
  'Danish',
  true
),
(
  'de',
  'German',
  true
),
(
  'dv',
  'Divehi',
  true
),
(
  'dz',
  'Dzongkha',
  true
),
(
  'ee',
  'Ewe',
  true
),
(
  'el',
  'Greek',
  true
),
(
  'en',
  'English',
  true
),
(
  'eo',
  'Esperanto',
  true
),
(
  'es',
  'Spanish',
  true
),
(
  'et',
  'Estonian',
  true
),
(
  'eu',
  'Basque',
  true
),
(
  'fa',
  'Persian',
  true
),
(
  'ff',
  'Peul',
  true
),
(
  'fi',
  'Finnish',
  true
),
(
  'fj',
  'Fijian',
  true
),
(
  'fo',
  'Faroese',
  true
),
(
  'fr',
  'French',
  true
),
(
  'fy',
  'West Frisian',
  true
),
(
  'ga',
  'Irish',
  true
),
(
  'gd',
  'Scottish Gaelic',
  true
),
(
  'gl',
  'Galician',
  true
),
(
  'gn',
  'Guarani',
  true
),
(
  'gu',
  'Gujarati',
  true
),
(
  'gv',
  'Manx',
  true
),
(
  'ha',
  'Hausa',
  true
),
(
  'he',
  'Hebrew',
  true
),
(
  'hi',
  'Hindi',
  true
),
(
  'ho',
  'Hiri Motu',
  true
),
(
  'hr',
  'Croatian',
  true
),
(
  'ht',
  'Haitian',
  true
),
(
  'hu',
  'Hungarian',
  true
),
(
  'hy',
  'Armenian',
  true
),
(
  'hz',
  'Herero',
  true
),
(
  'ia',
  'Interlingua',
  true
),
(
  'id',
  'Indonesian',
  true
),
(
  'ie',
  'Interlingue',
  true
),
(
  'ig',
  'Igbo',
  true
),
(
  'ii',
  'Sichuan Yi',
  true
),
(
  'ik',
  'Inupiak',
  true
),
(
  'io',
  'Ido',
  true
),
(
  'is',
  'Icelandic',
  true
),
(
  'it',
  'Italian',
  true
),
(
  'iu',
  'Inuktitut',
  true
),
(
  'ja',
  'Japanese',
  true
),
(
  'jv',
  'Javanese',
  true
),
(
  'ka',
  'Georgian',
  true
),
(
  'kg',
  'Kongo',
  true
),
(
  'ki',
  'Kikuyu',
  true
),
(
  'kj',
  'Kuanyama',
  true
),
(
  'kk',
  'Kazakh',
  true
),
(
  'kl',
  'Greenlandic',
  true
),
(
  'km',
  'Cambodian',
  true
),
(
  'kn',
  'Kannada',
  true
),
(
  'ko',
  'Korean',
  true
),
(
  'kr',
  'Kanuri',
  true
),
(
  'ks',
  'Kashmiri',
  true
),
(
  'ku',
  'Kurdish',
  true
),
(
  'kv',
  'Komi',
  true
),
(
  'kw',
  'Cornish',
  true
),
(
  'ky',
  'Kyrgyz',
  true
),
(
  'la',
  'Latin',
  true
),
(
  'lb',
  'Luxembourgish',
  true
),
(
  'lg',
  'Ganda',
  true
),
(
  'li',
  'Limburgian',
  true
),
(
  'ln',
  'Lingala',
  true
),
(
  'lo',
  'Laotian',
  true
),
(
  'lt',
  'Lithuanian',
  true
),
(
  'lu',
  'Luba-Katanga',
  true
),
(
  'lv',
  'Latvian',
  true
),
(
  'mg',
  'Malagasy',
  true
),
(
  'mh',
  'Marshallese',
  true
),
(
  'mi',
  'Maori',
  true
),
(
  'mk',
  'Macedonian',
  true
),
(
  'ml',
  'Malayalam',
  true
),
(
  'mn',
  'Mongolian',
  true
),
(
  'mo',
  'Moldovan',
  true
),
(
  'mr',
  'Marathi',
  true
),
(
  'ms',
  'Malay',
  true
),
(
  'mt',
  'Maltese',
  true
),
(
  'my',
  'Burmese',
  true
),
(
  'na',
  'Nauruan',
  true
),
(
  'nb',
  'Norwegian Bokmål',
  true
),
(
  'nd',
  'North Ndebele',
  true
),
(
  'ne',
  'Nepali',
  true
),
(
  'ng',
  'Ndonga',
  true
),
(
  'nl',
  'Dutch',
  true
),
(
  'nn',
  'Norwegian Nynorsk',
  true
),
(
  'no',
  'Norwegian',
  true
),
(
  'nr',
  'South Ndebele',
  true
),
(
  'nv',
  'Navajo',
  true
),
(
  'ny',
  'Chichewa',
  true
),
(
  'oc',
  'Occitan',
  true
),
(
  'oj',
  'Ojibwa',
  true
),
(
  'om',
  'Oromo',
  true
),
(
  'or',
  'Oriya',
  true
),
(
  'os',
  'Ossetian / Ossetic',
  true
),
(
  'pa',
  'Panjabi / Punjabi',
  true
),
(
  'pi',
  'Pali',
  true
),
(
  'pl',
  'Polish',
  true
),
(
  'ps',
  'Pashto',
  true
),
(
  'pt',
  'Portuguese',
  true
),
(
  'qu',
  'Quechua',
  true
),
(
  'rm',
  'Raeto Romance',
  true
),
(
  'rn',
  'Kirundi',
  true
),
(
  'ro',
  'Romanian',
  true
),
(
  'ru',
  'Russian',
  true
),
(
  'rw',
  'Rwandi',
  true
),
(
  'sa',
  'Sanskrit',
  true
),
(
  'sc',
  'Sardinian',
  true
),
(
  'sd',
  'Sindhi',
  true
),
(
  'se',
  'Northern Sami',
  true
),
(
  'sg',
  'Sango',
  true
),
(
  'sh',
  'Serbo-Croatian',
  true
),
(
  'si',
  'Sinhalese',
  true
),
(
  'sk',
  'Slovak',
  true
),
(
  'sl',
  'Slovenian',
  true
),
(
  'sm',
  'Samoan',
  true
),
(
  'sn',
  'Shona',
  true
),
(
  'so',
  'Somalia',
  true
),
(
  'sq',
  'Albanian',
  true
),
(
  'sr',
  'Serbian',
  true
),
(
  'ss',
  'Swati',
  true
),
(
  'st',
  'Southern Sotho',
  true
),
(
  'su',
  'Sundanese',
  true
),
(
  'sv',
  'Swedish',
  true
),
(
  'sw',
  'Swahili',
  true
),
(
  'ta',
  'Tamil',
  true
),
(
  'te',
  'Telugu',
  true
),
(
  'tg',
  'Tajik',
  true
),
(
  'th',
  'Thai',
  true
),
(
  'ti',
  'Tigrinya',
  true
),
(
  'tk',
  'Turkmen',
  true
),
(
  'tl',
  'Tagalog / Filipino',
  true
),
(
  'tn',
  'Tswana',
  true
),
(
  'to',
  'Tonga',
  true
),
(
  'tr',
  'Turkish',
  true
),
(
  'ts',
  'Tsonga',
  true
),
(
  'tt',
  'Tatar',
  true
),
(
  'tw',
  'Twi',
  true
),
(
  'ty',
  'Tahitian',
  true
),
(
  'ug',
  'Uyghur',
  true
),
(
  'uk',
  'Ukrainian',
  true
),
(
  'ur',
  'Urdu',
  true
),
(
  'uz',
  'Uzbek',
  true
),
(
  've',
  'Venda',
  true
),
(
  'vi',
  'Vietnamese',
  true
),
(
  'vo',
  'Volapük',
  true
),
(
  'wa',
  'Walloon',
  true
),
(
  'wo',
  'Wolof',
  true
),
(
  'xh',
  'Xhosa',
  true
),
(
  'yi',
  'Yiddish',
  true
),
(
  'yo',
  'Yoruba',
  true
),
(
  'za',
  'Zhuang',
  true
),
(
  'zh',
  'Chinese',
  true
),
(
  'zu',
  'Zulu',
  true
)
on conflict (code)
do update set
  name = excluded.name,
  is_active = true,
  updated_at = now();


-- ============================================================
-- 4. UNITS OF MEASURE
-- ============================================================

insert into public.units_of_measure (
  code,
  name,
  abbreviation,
  uom_type,
  conversion_factor,
  is_active
)
values
(
  'PCS',
  'Pieces',
  'pcs',
  'quantity',
  1,
  true
),
(
  'KG',
  'Kilogram',
  'kg',
  'weight',
  1,
  true
),
(
  'G',
  'Gram',
  'g',
  'weight',
  1,
  true
),
(
  'TON',
  'Metric Ton',
  't',
  'weight',
  1,
  true
),
(
  'LB',
  'Pound',
  'lb',
  'weight',
  1,
  true
),
(
  'M',
  'Meter',
  'm',
  'length',
  1,
  true
),
(
  'CM',
  'Centimeter',
  'cm',
  'length',
  1,
  true
),
(
  'MM',
  'Millimeter',
  'mm',
  'length',
  1,
  true
),
(
  'KM',
  'Kilometer',
  'km',
  'length',
  1,
  true
),
(
  'FT',
  'Foot',
  'ft',
  'length',
  1,
  true
),
(
  'IN',
  'Inch',
  'in',
  'length',
  1,
  true
),
(
  'L',
  'Liter',
  'L',
  'volume',
  1,
  true
),
(
  'ML',
  'Milliliter',
  'ml',
  'volume',
  1,
  true
),
(
  'M2',
  'Square Meter',
  'm²',
  'area',
  1,
  true
),
(
  'M3',
  'Cubic Meter',
  'm³',
  'volume',
  1,
  true
),
(
  'BOX',
  'Box',
  'box',
  'packaging',
  1,
  true
),
(
  'PACK',
  'Pack',
  'pack',
  'packaging',
  1,
  true
),
(
  'DOZ',
  'Dozen',
  'doz',
  'quantity',
  1,
  true
)
on conflict (code)
do update set
  name = excluded.name,
  abbreviation = excluded.abbreviation,
  uom_type = excluded.uom_type,
  conversion_factor = excluded.conversion_factor,
  is_active = true,
  updated_at = now();


-- ============================================================
-- 5. PAYMENT TERMS
-- ============================================================

insert into public.payment_terms (
  code,
  name,
  days_due,
  description,
  is_active
)
values
(
  'COD',
  'Cash on Delivery',
  0,
  'Payment is due immediately.',
  true
),
(
  'NET7',
  'Net 7',
  7,
  'Payment due within 7 days.',
  true
),
(
  'NET15',
  'Net 15',
  15,
  'Payment due within 15 days.',
  true
),
(
  'NET30',
  'Net 30',
  30,
  'Payment due within 30 days.',
  true
),
(
  'NET45',
  'Net 45',
  45,
  'Payment due within 45 days.',
  true
),
(
  'NET60',
  'Net 60',
  60,
  'Payment due within 60 days.',
  true
),
(
  'NET90',
  'Net 90',
  90,
  'Payment due within 90 days.',
  true
)
on conflict (code)
do update set
  name = excluded.name,
  days_due = excluded.days_due,
  description = excluded.description,
  is_active = true,
  updated_at = now();


-- ============================================================
-- 6. COUNTRY DEFAULT CURRENCIES
-- ============================================================

update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AFN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AF';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AX';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'ALL'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AL';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'DZD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'DZ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AS';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AD';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AOA'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XCD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AI';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XCD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'ARS'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AMD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AWG'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AW';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SHP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AC';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AUD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AU';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AT';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AZN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AZ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BSD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BS';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BHD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BH';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BDT'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BD';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BBD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BB';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BYN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BY';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BZD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BZ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XOF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BJ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BMD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BTN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BT';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BOB'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BQ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BAM'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BWP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BW';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NOK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BV';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BRL'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'IO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'VG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BND'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XOF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BF';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'BIF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BI';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'CVE'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CV';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'KHR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KH';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XAF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'CAD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'KYD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KY';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XAF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CF';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XAF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TD';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'CLP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CL';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'CNY'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AUD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CX';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AUD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CC';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'COP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'KMF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NZD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CK';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'CRC'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'HR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'CUP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CU';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XCG'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CW';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CY';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'CZK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CZ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'CDF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CD';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'DKK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'DK';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'DJF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'DJ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XCD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'DM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'DOP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'DO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TL';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'EC';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EGP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'EG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SV';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XAF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GQ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'ERN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'ER';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'EE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SZL'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SZ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'ETB'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'ET';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'FKP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'FK';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'DKK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'FO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'FJD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'FJ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'FI';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'FR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GF';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XPF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PF';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TF';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XAF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GMD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GEL'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'DE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GHS'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GH';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GIP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GI';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'DKK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GL';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XCD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GD';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GP';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GU';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GTQ'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GT';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GBP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GNF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XOF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GW';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GYD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GY';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'HTG'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'HT';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AUD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'HM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'HNL'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'HN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'HKD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'HK';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'HUF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'HU';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'ISK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'IS';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'INR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'IN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'IDR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'ID';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'IRR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'IR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'IQD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'IQ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'IE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GBP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'IM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'ILS'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'IL';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'IT';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XOF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CI';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'JMD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'JM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'JPY'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'JP';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GBP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'JE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'JOD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'JO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'KZT'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KZ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'KES'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AUD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KI';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'XK';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'KWD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KW';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'KGS'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'LAK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LV';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'LBP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LB';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'LSL'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LS';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'LRD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'LYD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LY';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'CHF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LI';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LT';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LU';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MOP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MGA'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MWK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MW';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MYR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MY';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MVR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MV';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XOF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'ML';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MT';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MH';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MQ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MRU'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MU';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'YT';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MXN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MX';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'FM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MDL'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MD';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MC';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MNT'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'ME';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XCD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MS';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MAD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MZN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MZ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MMK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NAD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AUD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NPR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NP';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NL';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XPF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NC';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NZD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NZ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NIO'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NI';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XOF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NGN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NZD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NU';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AUD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NF';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'KPW'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KP';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MKD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MK';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MP';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NOK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'NO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'OMR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'OM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'PKR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PK';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PW';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'ILS'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PS';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'PAB'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'PGK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'PYG'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PY';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'PEN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'PHP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PH';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NZD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'PLN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PL';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PT';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'QAR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'QA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XAF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'RE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'RON'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'RO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'RUB'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'RU';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'RWF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'RW';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'BL';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SHP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SH';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XCD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XCD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LC';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'MF';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'PM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XCD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'VC';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'WST'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'WS';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'STN'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'ST';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SAR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XOF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'RSD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'RS';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SCR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SC';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SLE'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SL';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SGD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XCG'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SX';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SK';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SI';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SBD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SB';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SOS'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'ZAR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'ZA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GBP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GS';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'KRW'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'KR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SSP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SS';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'ES';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'LKR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'LK';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SDG'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SD';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SRD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NOK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SJ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SEK'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'CHF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'CH';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SYP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'SY';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'TWD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TW';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'TJS'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TJ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'TZS'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TZ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'THB'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TH';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XOF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'NZD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TK';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'TOP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TO';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'TTD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TT';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'SHP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'TND'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'TRY'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TR';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'TMT'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TC';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AUD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'TV';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'UM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'VI';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'UGX'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'UG';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'UAH'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'UA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'AED'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'AE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'GBP'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'GB';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'USD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'US';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'UYU'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'UY';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'UZS'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'UZ';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'VUV'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'VU';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'EUR'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'VA';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'VES'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'VE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'VND'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'VN';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'XPF'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'WF';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'MAD'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'EH';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'YER'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'YE';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'ZMW'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'ZM';
update public.countries
set
  default_currency_id = (
    select id
    from public.currencies
    where code = 'ZWG'
    limit 1
  ),
  updated_at = now()
where iso2_code = 'ZW';


-- ============================================================
-- 7. VERIFICATION
-- ============================================================

do $$
declare
  currency_count integer;
  country_count integer;
  language_count integer;
  uom_count integer;
  payment_term_count integer;
begin

  select count(*)
  into currency_count
  from public.currencies
  where is_active = true;

  select count(*)
  into country_count
  from public.countries
  where is_active = true;

  select count(*)
  into language_count
  from public.languages
  where is_active = true;

  select count(*)
  into uom_count
  from public.units_of_measure
  where is_active = true;

  select count(*)
  into payment_term_count
  from public.payment_terms
  where is_active = true;


  if currency_count = 0 then
    raise exception
      'Global seed failed: no active currencies found.';
  end if;

  if country_count = 0 then
    raise exception
      'Global seed failed: no active countries found.';
  end if;

  if language_count = 0 then
    raise exception
      'Global seed failed: no active languages found.';
  end if;

  if uom_count = 0 then
    raise exception
      'Global seed failed: no active units of measure found.';
  end if;

  if payment_term_count = 0 then
    raise exception
      'Global seed failed: no active payment terms found.';
  end if;


  raise notice
    'Elvaris global seed completed: % currencies, % countries, % languages, % UOMs, % payment terms.',
    currency_count,
    country_count,
    language_count,
    uom_count,
    payment_term_count;

end
$$;
