-- ============================================================
-- ELVARIS ERP
-- Migration 032
-- Journal Preferences
-- ============================================================
--
-- Purpose:
--   Configure Journal Voucher behavior for the company.
--
-- Features:
--
--   1. Enable / disable Branch on journal transactions
--   2. Allow / disallow manual Journal Numbers
--   3. Protect Journal Number uniqueness
--
-- Current recommended MO settings:
--
--   branch_accounting_enabled = false
--   allow_manual_journal_number = true
--
-- ============================================================


-- ============================================================
-- 1. COMPANY JOURNAL PREFERENCES
-- ============================================================

alter table public.companies
add column if not exists
    branch_accounting_enabled boolean
    not null
    default false;


alter table public.companies
add column if not exists
    allow_manual_journal_number boolean
    not null
    default true;


-- ============================================================
-- 2. DOCUMENTATION
-- ============================================================

comment on column public.companies.branch_accounting_enabled
is
    'Controls whether Branch is available on financial transactions.';


comment on column public.companies.allow_manual_journal_number
is
    'Controls whether an authorized user may enter a Journal Number manually.';


-- ============================================================
-- 3. JOURNAL NUMBER UNIQUENESS
-- ============================================================

create unique index if not exists
ux_journal_entries_company_journal_number
on public.journal_entries (
    company_id,
    journal_number
);


-- ============================================================
-- 4. UPDATE UNIVERSAL JOURNAL TRANSACTION CREATION
-- ============================================================
--
-- Manual number:
--
--   allowed when company setting = true
--
-- Automatic:
--
--   generated by universal JV numbering profile
--
-- Branch:
--
--   accepted only when branch accounting is enabled.
--
-- ============================================================

create or replace function public.create_journal_transaction(
    p_company_id uuid,
    p_entry_date date,
    p_description text default null,
    p_branch_id uuid default null,
    p_source_type public.journal_source_type default 'general_journal',
    p_currency_id uuid default null,
    p_reference_type varchar(50) default null,
    p_reference_number varchar(80) default null,
    p_manual_journal_number varchar(40) default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $function$

declare

    v_journal_id uuid;

    v_journal_number varchar(40);

    v_fiscal_year_id uuid;

    v_period_id uuid;

    v_branch_enabled boolean;

    v_manual_number_allowed boolean;

begin

    -- --------------------------------------------------------
    -- Company
    -- --------------------------------------------------------

    select
        branch_accounting_enabled,
        allow_manual_journal_number
    into
        v_branch_enabled,
        v_manual_number_allowed
    from public.companies
    where id = p_company_id
      and is_active = true;


    if not found then

        raise exception
            'Active company does not exist.';

    end if;


    -- --------------------------------------------------------
    -- Branch
    -- --------------------------------------------------------

    if p_branch_id is not null then

        if v_branch_enabled = false then

            raise exception
                'Branch accounting is disabled for this company.';

        end if;


        if not exists (
            select 1
            from public.branches b
            where b.id = p_branch_id
              and b.company_id = p_company_id
              and b.is_active = true
        ) then

            raise exception
                'Branch does not belong to the company or is inactive.';

        end if;

    end if;


    -- --------------------------------------------------------
    -- Date
    -- --------------------------------------------------------

    if p_entry_date is null then

        raise exception
            'Entry date is required.';

    end if;


    -- --------------------------------------------------------
    -- Fiscal year / accounting period
    -- --------------------------------------------------------

    select
        r.fiscal_year_id,
        r.accounting_period_id
    into
        v_fiscal_year_id,
        v_period_id
    from public.resolve_accounting_period(
        p_company_id,
        p_entry_date
    ) r
    limit 1;


    if v_fiscal_year_id is null
       or v_period_id is null
    then

        raise exception
            'No open fiscal year/accounting period exists for date %.',
            p_entry_date;

    end if;


    -- --------------------------------------------------------
    -- Journal Number
    -- --------------------------------------------------------

    if nullif(
        trim(p_manual_journal_number),
        ''
    ) is not null
    then

        if v_manual_number_allowed = false then

            raise exception
                'Manual Journal Number entry is disabled in company settings.';

        end if;


        v_journal_number :=
            trim(
                p_manual_journal_number
            );

    else

        v_journal_number :=
            public.next_reference_number(
                p_company_id,
                'JV',
                p_entry_date
            );

    end if;


    -- --------------------------------------------------------
    -- Prevent duplicate Journal Number
    -- --------------------------------------------------------

    if exists (
        select 1
        from public.journal_entries je
        where je.company_id = p_company_id
          and je.journal_number =
              v_journal_number
    ) then

        raise exception
            'Journal Number "%" already exists for this company.',
            v_journal_number;

    end if;


    -- --------------------------------------------------------
    -- Create draft journal
    -- --------------------------------------------------------

    insert into public.journal_entries (
        company_id,
        branch_id,
        journal_number,
        entry_date,
        source_type,
        description,
        status,
        currency_id,
        exchange_rate,
        fiscal_year_id,
        accounting_period_id,
        reference_type,
        reference_number,
        is_reversal,
        created_at,
        created_by,
        updated_at,
        updated_by
    )
    values (
        p_company_id,
        p_branch_id,
        v_journal_number,
        p_entry_date,
        p_source_type,
        p_description,
        'draft'::public.journal_entry_status,
        p_currency_id,
        1,
        v_fiscal_year_id,
        v_period_id,
        p_reference_type,
        p_reference_number,
        false,
        now(),
        auth.uid(),
        now(),
        auth.uid()
    )
    returning id
    into v_journal_id;


    return v_journal_id;

end;
$function$;


-- ============================================================
-- 5. KEEP LEGACY CREATE FUNCTION COMPATIBLE
-- ============================================================

create or replace function public.create_journal_entry(
    p_company_id uuid,
    p_entry_date date,
    p_description text default null,
    p_branch_id uuid default null,
    p_source_type public.journal_source_type default 'general_journal',
    p_currency_id uuid default null,
    p_reference_type varchar(50) default null,
    p_reference_number varchar(80) default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $function$

begin

    return public.create_journal_transaction(
        p_company_id,
        p_entry_date,
        p_description,
        p_branch_id,
        p_source_type,
        p_currency_id,
        p_reference_type,
        p_reference_number,
        null
    );

end;
$function$;


-- ============================================================
-- 6. VALIDATION
-- ============================================================

do $$
declare

    v_branch_setting boolean;

    v_manual_setting boolean;

begin

    select
        branch_accounting_enabled,
        allow_manual_journal_number
    into
        v_branch_setting,
        v_manual_setting
    from public.companies
    where company_code = 'MO'
    limit 1;


    if v_branch_setting is null then

        raise exception
            'branch_accounting_enabled was not created correctly.';

    end if;


    if v_manual_setting is null then

        raise exception
            'allow_manual_journal_number was not created correctly.';

    end if;


    if not exists (
        select 1
        from pg_indexes
        where schemaname = 'public'
          and indexname =
              'ux_journal_entries_company_journal_number'
    ) then

        raise exception
            'Journal Number uniqueness index was not created.';

    end if;

end
$$;


-- ============================================================
-- END MIGRATION 032
-- ============================================================